### ISSUE TITLE
Mask Images

### ISSUE THREAD

**Issue by dreamstorm25** [piperod/beepose#1]
I have three questions regarding the mask images - 
1. Does the function get_masks(self, annotations) in pose_dataset.py produces masks for each images using all the annotations associated with that image at a time ? 
2. what is the purpose of mask_miss ?
3. Does the function not store the masks like in your dataset but only use them while running ?

**Comment by piperod** [comment]
Hi @dreamstorm25 great questions. Mask are suppose to be used when data is not completely label. For example, say that you have 100 visible  bees but you only label 20, the rest would be detected by the model but since they were not labeled the model would think they are false positives. Right now, we are not using the masks as we fully label our images and we were getting some errors in the training process, our plan is to put that functionality back as soon as possible, but in principle you should be able to use the code if your images are fully labeled. Hope to get this working again soon.

**Comment by dreamstorm25** [comment]
Gotcha, thanks !
