### ISSUE TITLE
Huge difference in Stage L1_acc vs L2_acc

### ISSUE THREAD

**Issue by dreamstorm25** [piperod/beepose#9]
During training, I have observed that there is a huge difference between the L1_acc and L2_acc of any stage. While L2_acc has gone over 0.99 and is steadily increasing, L1_acc is unstable as it increases and decreases without any pattern. As I understand, L1_acc is about the groundtruths and L2_acc is for PAFs. Is this behavior possible and is the accuracy of groundtruths not related to PAFs ?
![Stage1_acc](https://user-images.githubusercontent.com/22818339/75497904-4ae3f100-598b-11ea-8315-9b9f52c48a7e.png)

**Comment by piperod** [comment]
The problem here is that since it is at pixel level and it is averaging over the image, its possible that some mild detections cause a problem for negatives. At testing time we threshold the detections to avoid this, but yeah I know those numbers are kind of non informative at all when training. I think we should work on incorporating better metrics to check training.
